#!/bin/bash

EXIT_PHPCS_NO_BIN=1
EXIT_PHPCS_ERROR=2
EXIT_PHP_LINT_ERROR=3
EXIT_JSHINT_NO_BIN=4
EXIT_JSHINT_ERROR=5

function pre_exit {
  #-- Restore our stashed files
  git reset --hard
  git stash pop --quiet --index
}

function error {
  echo -e "\n\n== ERROR: $1\n"
  pre_exit
  exit $2
}


function check_phpcs {
  PHP_FILES="`echo -e \"${FILES_MODIFIED}\n${FILES_ADDED}\" | grep '\.php$'`"
  if [ -n "$PHP_FILES" ]; then

    #-- Make sure they have PHP_CodeSniffer installed
    if [ ! `which phpcs` ]; then
      error "could not find phpcs.  See http://pear.php.net/package/PHP_CodeSniffer" $EXIT_PHPCS_NO_BIN
    fi

    echo -e "== Running PHP_CodeSniffer on the following files:\n$PHP_FILES\n"
    phpcs --standard=UseAllFive "$PHP_FILES"
    ret=$?
    echo "phpcs returned: $ret"
    if [ 0 -ne $ret ]; then
      error "You have PHP errors!" $EXIT_PHPCS_ERROR
    fi
  fi
}


function check_phplint {
  local ret=0
  PHP_FILES="`echo -e \"${FILES_MODIFIED}\n${FILES_ADDED}\" | grep '\.php$'`"
  if [ -n "$PHP_FILES" ]; then

    echo -e "== Running php -l on the following files:\n$PHP_FILES\n"
    for f in $PHP_FILES; do
      php -l $f | grep -v 'No syntax errors detected in'
      if [ 0 -eq $? ]; then
        ret=1
      fi
    done
    if [ 0 -ne $ret ]; then
      error "You have PHP syntax errors!" $EXIT_PHP_LINT_ERROR
    fi
  fi
}


function check_jshint {
  JS_FILES="`echo -e \"${FILES_MODIFIED}\n${FILES_ADDED}\" | grep '\.js$'`"
  if [ -n "$JS_FILES" ]; then

    #-- Make sure they have jshint installed
    if [ ! `which jshint` ]; then
      error "could not find jshint.  See http://jshint.com/" $EXIT_JSHINT_NO_BIN
    fi

    echo -e "== Running js_hint on the following files:\n$JS_FILES\n"
    jshint "$JS_FILES"
    if [ 0 -ne $? ]; then
      error "You have JS errors!" $EXIT_JSHINT_ERROR
    fi
  fi
}


#-----------------#
#   SCRIPT CODE   #
#-----------------#
#-- CD to the root git dir
cd "`dirname $0`/../.."

#-- Stash all changes so we can check what we are actually committing
git stash --include-untracked --keep-index

FILES_ADDED="`git diff --cached --name-only --diff-filter=M`"
FILES_MODIFIED="`git diff --cached --name-only --diff-filter=A`"
FILES_DELETED="`git diff --cached --name-only --diff-filter=D`"

check_phpcs
check_phplint
check_jshint

pre_exit
